stack: terom/whoami
version: 0.1.0
expose: whoami
variables:
  scale:
    type: integer
    from:
        env: WHOAMI_SCALE
    default: 4
  path:
    type: string
    from:
        env: WHOAMI_PATH
    default: /whoami
services:
    whoami:
        image: registry.${GRID}.kontena.local/whoami
        build: .
        instances: ${scale}
