stack: terom/whoami
version: 0.1.0
expose: whoami
variables:
  scale:
    type: integer
    from:
        env: WHOAMI_SCALE
    default: 4
  path:
    type: string
    from:
        env: WHOAMI_PATH
    default: /whoami
services:
    whoami:
      image: registry.${GRID}.kontena.local/whoami
      build: .
      instances: ${scale}
      environment:
        io.kontena.nginx.service: whoami
        io.kontena.nginx.tcp: 8000
        io.kontena.nginx.udp: 8000
        io.kontena.nginx.http: 8000
        io.kontena.nginx.http.location: /whoami
